### ISSUE TITLE
`rbnotes show`  crashes when a valid but non-existing timestamp is passed

### ISSUE THREAD

**Issue by mnbi** [mnbi/rbnotes#100]
Execute the following command:

``` shell
> rbnotes show 20991231235960
```

Then, it crashes.  Ruby says:

``` shell
/Users/mnbi/.gem/ruby/3.0.0/gems/textrepo-0.5.8/lib/textrepo/file_system_repository.rb:124:in `read': missing timestamp: 29991231235659 (Textrepo::MissingTimestampError)
	from /Users/mnbi/.gem/ruby/3.0.0/gems/rbnotes-0.4.13/lib/rbnotes/commands/show.rb:25:in `block in execute'
	from /Users/mnbi/.gem/ruby/3.0.0/gems/rbnotes-0.4.13/lib/rbnotes/commands/show.rb:25:in `map'
	from /Users/mnbi/.gem/ruby/3.0.0/gems/rbnotes-0.4.13/lib/rbnotes/commands/show.rb:25:in `execute'
	from /Users/mnbi/.gem/ruby/3.0.0/gems/rbnotes-0.4.13/exe/rbnotes:43:in `run'
	from /Users/mnbi/.gem/ruby/3.0.0/gems/rbnotes-0.4.13/exe/rbnotes:50:in `<top (required)>'
	from /Users/mnbi/.gem/ruby/3.0.0/bin/rbnotes:23:in `load'
	from /Users/mnbi/.gem/ruby/3.0.0/bin/rbnotes:23:in `<main>'
```

**Comment by mnbi** [comment]
`Textrepo::FileSystemRepository#read` may raise an exception when a file does not exist which is associated to the given timestamp.  It works as designed.  However, `Rbnotes::Commands::Show#execute` does not handle the exception even if it call the method.  This is the cause of the symptom.

**Comment by mnbi** [comment]
Fix will be:

- catch `Textrepo::MissingTimestampError` at `Show#execute`,
- raise `Rbnotes::MissingTimestampError` which has been already caught at the toplevel.
